### ISSUE TITLE
Why do we need SetDoNotWaitForThreads with windows 7 when linking to ITK statically 

### ISSUE THREAD

**Issue by Siron777** [InsightSoftwareConsortium/ITK#1028]
Hi,

We are using itk 5.0.0 as a static library on windows, with visual studio 2017. We have encountered some dead locks preventing the unit tests using ITK to terminate. This is only happening on windows 7, not windows 10. It seems that we need to use the method SetDoNotWaitForThreads (https://github.com/InsightSoftwareConsortium/ITK/commit/86b7cce95a6b1515c8243cf91d052317d3ae2407).

I would like to get more information on the reason of this issue. Why is it only on windows 7 and not windows 10 ? The method SetDoNotWaitForThreads  is a temporary work around to an unknown root cause ?

Thank you.

**Comment by dzenanz** [comment]
I don't know why would there be a difference between Windows 7 and 10. Are you sure that nothing else is different?

As to why waiting for threads is needed in static case, but not dynamic, it is described in this [comment](https://github.com/InsightSoftwareConsortium/ITK/commit/86b7cce95a6b1515c8243cf91d052317d3ae2407#diff-595b2adcc597f969ff47a6ec080c783eR304). Essentially, in DLL case the OS has already killed the threads, so trying to wait for them causes a deadlock. Whereas in static case, if we don't wait for threads assertions in debug mode complain about not doing things right - in release mode it does not cause an issue because OS completely cleans up our resources shortly thereafter.

**Comment by dzenanz** [comment]
Fixed by #1052.
