### ISSUE TITLE
Expose number of threads control in Python

### ISSUE THREAD

**Issue by mrocklin** [InsightSoftwareConsortium/ITK#1137]
It looks like I can control the number of threads in C++ with the following:

```python
itk::MultiThreader::SetGlobalDefaultUseThreadPool(true);
itk::MultiThreaderBase::SetGlobalDefaultNumberOfThreads( n );
```

Is it possible to also do this from within Python today?

It seems like I can use environment variables for now, but it'd be nice to have control from within Python as well if possible

```
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
ITK_USE_THREADPOOL
```

**Comment by mrocklin** [comment]
I'll bump this once to keep it alive, and then let it decay on the next round if there are no comments.

**Comment by thewtex** [comment]
@mrocklin thanks for reporting this issue and the follow-up! :pray: 

The interface is available in Python, but it is not obvious how to access it since it is a C++ static method.

Please review this example that demonstrates how to access this method:

https://github.com/InsightSoftwareConsortium/ITKExamples/pull/149

**Comment by thewtex** [comment]
Convenience function suggested by @mrocklin added in #1925
