### ISSUE TITLE
Python GetArrayViewFromImage doesn't raise error if used the wrong way

### ISSUE THREAD

**Issue by MohamedKiouaz** [InsightSoftwareConsortium/ITK#1566]
### Description
The following code :
```
image = itk.imread(file_path)
image = itk.GetArrayViewFromImage(image)
image[0]
```
creates an invalid numpy array.
This cannot be seen right away and causes a delayed crash of python the moment when the array is actually used.
This is unexpected since the following code works in Numpy : 
```
A = np.zeros((10, 10))
A = A[5:, :]
print(A)
```

### Expected behavior

Raise any kind of error, or produce a valid numpy array.

### Actual behavior

Nothing happens immediately. Cannot be debugged. The software crashes later without any error (not even segfault).

### Reproducibility

100%

### Versions & Environment

ITK 5.0.1 with Python 3.7.4 64-bit on Windows 10 1909

**Comment by thewtex** [comment]
The `View` in the function name is referring to the [NumPy view](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html) concept. This saves memory but comes with a restriction / limitation: the original `image` instance must be kept around, or undefined behaviour will occur. In this example,

``` 
image = itk.imread(file_path)
image = itk.GetArrayViewFromImage(image)
```

Assigning the result in the second line is removing the original `image` -- it needs to be around for `image` to be valid.

Since `GetArrayViewFromImage` does not know what its result is being assigned to, it is difficult to throw an error here.

There are two options:

1. Use `GetArrayFromImage` or `array_from_image`. This is safe.
2. Assign to a different variable name, i.e.

```
image = itk.imread(file_path)
image = itk.GetArrayFromImage(image)
```

**Comment by MohamedKiouaz** [comment]
Thanks for the reply @thewtex.

Do you have an idea about why such bug doesn't happen in pure Numpy ? Assigning a view to the original numpy array does not destroy the array. The code below doesn't make the python crash.

```
A = np.zeros((10, 10))
A = A[5:, :] # Create a view of A and assign it to A.
print(A) # No crash
```

Even if we can't fix it, I think it is important to find the reason behind this weird behavior.
