### ISSUE TITLE
module 'itk' has no attribute 'SyNImageRegistrationMethod'

### ISSUE THREAD

**Issue by qiang-zhang-neu** [InsightSoftwareConsortium/ITK#1569]
I want to use SyNImageRegistrationMethod in itk, but I can not import it. 

First, I install itk by pip, and the version is 5.0.1. It report that:

`module 'itk' has no attribute 'SyNImageRegistrationMethod'`

Then, I compile ITK from source and wrap it with python, and it also report that: 

`module 'itk' has no attribute 'SyNImageRegistrationMethod'`

How can I use the SyN algorithm in ITK? Could someone provide a demo to use the SyN algorithm? I can not find any demo to use it.

**Comment by dzenanz** [comment]
@PranjalSahu was this fixed by some of your recent contributions?

**Comment by PranjalSahu** [comment]
So it was added in this commit [SyNImageRegistrationMethod](https://github.com/InsightSoftwareConsortium/ITK/commit/3e27a461246b484e80701d7be249596e1ebfdbc2#diff-95c50b0b0362c9edf644ba40c343e9064b9f037a512ed88a43c29aa6c11e57d4). 

I added the support for Mesh for the ThinShellDemons in the recent [commit].(https://github.com/InsightSoftwareConsortium/ITK/commit/653ab122ea58953094f36c88dd618acb8acc3666#diff-95c50b0b0362c9edf644ba40c343e9064b9f037a512ed88a43c29aa6c11e57d4) 
So this issue was already solved.
