### ISSUE TITLE
OpenCVBridge Compile error ITK 5.1RC1

### ISSUE THREAD

**Issue by Hicham-Damae** [InsightSoftwareConsortium/ITK#1651]
### Description
I managed to compile ITK 5.1RC1 with OpenCV Bridge, after some corrections (already fixed on master or ongoing). 
Everything works pretty well, except when I use OpenCVImageBridge function.

I have the folowing error : 
C:\Program Files\ITK\Release\include\ITK-5.1\itkOpenCVImageBridge.hxx(98): error C2440: 'initializing': cannot convert from 'const cv::Mat' to 'const IplImage'

I fixed this error using
```C++
const IplImage converted = cvIplImage(in);
instead of 
const IplImage converted = in;
```
on line 98 (itkOpenCVImageBridge.hxx) 

### Versions
OpenCV 4.2
ITK 5.1RC1

### Environment
Windows 10 x64 
MSVC 2019 16.4

**Comment by dzenanz** [comment]
Is this issue still open? #1650 might have touched it.

**Comment by Giaco90** [comment]
@Hicham-Damae solution worked for ITK 5.0.1 and OpenCV 4.2.0 too.

**Comment by dzenanz** [comment]
Can either of you turn it into a [PR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by PierreWargnier** [comment]
Hi, I was having the same error with ITK 5.2.0 and OpenCV 4.3.0 (latest stable version of both). The solution proposed by @Hicham-Damae works for me too. This is due to the fact that IplImage has been deprecated in OpenCV for quite a long time now. It was eventually removed in version 4.0.0 and only remains in the C API. The fix works because it is explicitely invoking the C API. This however, is only a temporary fix because the OpenCV C API is likely to be completely removed in future versions (it is already absent from the documentation as of version 4.3.0 - see [https://docs.opencv.org/4.3.0/](https://docs.opencv.org/4.3.0/) - although it appears to be still accessible).
