### ISSUE TITLE
[ITK 5.1|Windows] Including wrong Python library path.

### ISSUE THREAD

**Issue by Neumann-A** [InsightSoftwareConsortium/ITK#1804]
### Description
https://github.com/InsightSoftwareConsortium/ITK/blob/7900a8b6d63ec8201405eff3b46c8d2a4e563c45/Wrapping/Generators/Python/CMakeLists.txt#L235-L241
Needs to be aware about the configuration and add the correct folder. `python<ver>.lib (Python3_LIBRARY_RELEASE) `and `python<ver>_d.lib (Python3_LIBRARY_DEBUG)` are not required to be on the same path. 
Why does this not use `target_link_libraries` with `Python3_LIBRARIES`?

**Comment by thewtex** [comment]
We have had many issues with the FindPython3 module returning the wrong results across the multiple use cases we have. `Python3_LIBRARY`, which can be passed explicitly to the build, is used here for reliability. `link_directories` is used instead of `target_link_directories` because we support CMake 3.10.2, which does not have `target_link_directories`.

> Why does this not use target_link_libraries with Python3_LIBRARIES?

`target_link_libraries` is used here:

https://github.com/InsightSoftwareConsortium/ITK/blob/7900a8b6d63ec8201405eff3b46c8d2a4e563c45/Wrapping/Generators/Python/CMakeLists.txt#L473

Does changing this to:

```
if(NOT Python3_LIBRARY AND Python3_LIBRARIES)
    itk_target_link_libraries_with_dynamic_lookup(${lib} LINK_PUBLIC ${Python3_LIBRARIES})
elseif(Python3_LIBRARY)
    itk_target_link_libraries_with_dynamic_lookup(${lib} LINK_PUBLIC ${Python3_LIBRARY})
else()
    itk_target_link_libraries_with_dynamic_lookup(${lib} LINK_PUBLIC ${PYTHON_LIBRARY})
endif()
```

address your use case?

**Comment by Neumann-A** [comment]
No since 
`link_directories(${python_library_directory}) `
adds the wrong link directory in vcpkg.

But I solved It by passing `Python3_LIBRARY` depending on Release/Debug configuration. Still find there should be another solution without knowing ITK internals.

**Comment by thewtex** [comment]
Should be addressed by https://github.com/InsightSoftwareConsortium/ITK/pull/2081
