### ISSUE TITLE
Add __dict__ method for itk.MetaDataDictionary

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#1957]
# Description

Add a `__dict__` method to itk.MetaDataDictionary so a Python `dict` representation can be obtained with

```
meta_dict = dict(meta_data_dictionary)
```

xref https://github.com/Project-MONAI/MONAI/issues/856

### Additional Information

Reasonable implementation:

```
meta_dict = {}
for key in img_meta_dict.GetKeys():
    # Ignore deprecated, legacy members that cause issues
    if key.startswith('ITK_original_'):
        continue
    meta_dict[key] = img_meta_dict[key]
meta_dict['origin'] = np.asarray(img.GetOrigin())
meta_dict['spacing'] = np.asarray(img.GetSpacing())
meta_dict['direction'] = itk.array_from_matrix(img.GetDirection())
```

This can be added to `def __dict__(self)` here: https://github.com/InsightSoftwareConsortium/ITK/blob/b2dcce79bb231b285acc540098fc5d032490ee34/Wrapping/Generators/Python/PyBase/pyBase.i#L124-L158

along with a test.

**Comment by thewtex** [comment]
Addressed in https://github.com/InsightSoftwareConsortium/ITK/pull/2039

**Comment by jond01** [comment]
(Sorry for the delayed comment)

Very nice! I like the development of itk towards a more pythonic interface.

I have a few comments:

1. Regarding the `'origin'`, `'direction'` and `'spacing'` keys - it might be better to consider them as properties of the image class rather than semi-dictionary keys (through the general `__getitem__` and `__setitem__` methods).
I prefer `image.origin = [4.0, 2.0, 2.0]` over `image['origin'] = [4.0, 2.0, 2.0]`.
Additionally, it will remove these keys from the metadata:
```
 ...
 '0028|1052': '-01.024000E+03',
 '0028|1053': '001.000000E+00',
 'origin': array([-836., -144., -122.]),
 'spacing': array([1.      , 0.484375, 0.484375]),
 'direction': array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])}
```
Maybe more appropriate since they are not really tags in the header

2. Not completely related to the topic - is there any plan to support sequences in the metadata object? Looks like they are omitted both in C++ and python.
