### ISSUE TITLE
Python Wrapping not working with CMake 3.18

### ISSUE THREAD

**Issue by MrTzschr** [InsightSoftwareConsortium/ITK#2049]
### Description

Compiling ITK 5.1.1 with Python Wrapping enabled fails using CMake 3.18.4 due to missing python3x.lib. Using CMake 3.17.5 works fine.

### Steps to Reproduce

Configure ITK in CMake with ```ITK_WRAP_PYTHON=ON```.
Build the project using MSVC from Visual Studio 2019.

### Expected behavior

Build finishing without errors.

### Actual behavior

Build fails with:
```LINK : fatal error LNK1104: cannot open file 'python38.lib'```

### Reproducibility

100%

### Versions

ITK 5.1.1 master
Windows 10
Python 3.8.3 from Anaconda3 (2020.07)
CMake 3.17.5/3.18.4
Visual Studio 2019 v16.7.5

### Additional Information

Both CMake versions report the correct Python version, e.g.
```-- Found Python3: C:/[...]/Anaconda3/python.exe (found version "3.8.3") found components: Interpreter Development Development.Module Development.Embed ```.
CMake variables like ```_Python3_EXECUTABLE```, ```_Python3_LIBRARY_RELEASE``` and ```_Python3_RUNTIME_LIBRARY_RELEASE``` have valid contents.

**Comment by dzenanz** [comment]
This happens with CMake 3.18.2 as well. But this is [a bug in CMake](https://gitlab.kitware.com/cmake/cmake/-/issues/21285), not ITK. Thanks for reporting this, I didn't know why Python build is failing on my lapop.

**Comment by MarkaPola** [comment]
Are you sure to use the right artifact variable? Because if the result of `find_package` is  successful, there is no reason for the link to failed.

If you don't use the imported targets (`Python3::Python` or `Python3::Module`), the variable defining libraries is `Python3_LIBRARIES`, nothing else should be used (please note the absence of underscore at the beginning and the presence of an 'S' at the end). Moreover, this variable **IS NOT** a cache variable so ensure the scope of this variable is correct against your usage.  
So please check again to ensure you use the right variable.

All variables beginning with an underscore are **private** and **MUST NOT** be used.

And to finish, for now an [issue](https://gitlab.kitware.com/cmake/cmake/-/issues/21285) is logged, but no bug is confirmed so far.

**Comment by MrTzschr** [comment]
@dzenanz thanks for the confirmation and link.

With the input of @MarkaPola it should be enough to change the variable `Python3_LIBRARY` to `Python3_LIBRARIES` in [this part](https://github.com/InsightSoftwareConsortium/ITK/blob/fd6cc5ab659cba3c4d5e9207a7c48a6820ca7fa3/Wrapping/Generators/Python/CMakeLists.txt#L237), right?

**Comment by dzenanz** [comment]
@MrTzschr Is that the problem? Can you test it on your local machine?

**Comment by MrTzschr** [comment]
@dzenanz compiling now and will report back

**Comment by MrTzschr** [comment]
@dzenanz Looks good on my side, can you verify this?

**Comment by N-Dekker** [comment]
I encounter the same issue, trying to build https://github.com/InsightSoftwareConsortium/ITKElastix so thanks!
