### ISSUE TITLE
Point data stored wrong by MeshGiftiIO

### ISSUE THREAD

**Issue by crossmanith** [InsightSoftwareConsortium/ITK#2092]
### Description

Values in gifti data arrays can be stored in ROW MAJOR ORDER (x1, x2, x3, ..., x_n, y1, y2, ..., y_n, z1, z2, ..., z_n) or COLUMN MAJOR ORDER (x1, y1, z1, x2, y2, z2, ..., x_n, y_n, z_n). 

### Steps to Reproduce

https://gist.github.com/crossmanith/51adfc8600b050f639e816d100fc5464

### Expected behavior

-> gist

### Actual behavior

-> gist

### Reproducibility

100%

### Versions

ITK 5.2.0 / 2b92d3973c

### Environment

ubuntu 20.04, cmake 3.16.3, gcc 9.3.0

### Additional Information

none

**Comment by dzenanz** [comment]
I think you got the opposite understanding of row major/column major organization. See [Wikipedia article](https://en.wikipedia.org/wiki/Row-_and_column-major_order) on it. Instead of 2x2 matrix in your MWE, maybe use 3x7 matrix? There should be less possibility for confusion that way. Or find some sample GIfTI files which could be used for testing.

**Comment by crossmanith** [comment]
Let's assume we have two points P(1|2|3) and Q(4|5|6). What would be the correct order of values 1...6 if we store them in row major order?

Maybe my misunderstanding is about how ITK stores vector information...

**Comment by dzenanz** [comment]
I believe that row major would be 123456 and column major would be 142536.

**Comment by crossmanith** [comment]
Misunderstanding on my side -> not a bug
