### ISSUE TITLE
PR switching from qform to sform causing many downstream support issues, particularly for small voxel sizes

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#2674]
The PR here, https://github.com/InsightSoftwareConsortium/ITK/pull/1868

Is regularly triggering issues in various downstream projects, with users with (wrong? malformed? other?) NIFTI files which used to work with ITK-based tools and now do not.

https://github.com/Project-MONAI/MONAILabel/issues/35
https://github.com/CoBrALab/RABIES/issues/160
https://github.com/ANTsX/ANTs/issues/1213
https://github.com/SimpleITK/SimpleITK/issues/1433

I'm not sure what the solution to this is, but I'd like to propose a couple:

1. Change code to be a warning and fallthrough to qform reading
2. Provide a more informative error for the user to correct the generation of the invalid NIFTI file

**Comment by dzenanz** [comment]
People who use NIFTI a lot should weigh in. Candidates: @hjmjohnson @cookpa @vfonov @seanm @lassoan.

**Comment by cookpa** [comment]
The code does attempt to fall back to the qform if the sform cannot be used. The ANTs bug you link to was triggered by a combination of small voxels and missing qform (qform_code == 0). If I increased the voxel size, or entered a qform into the header, it worked. 

I haven't had time to chase it down but I think there is some numerical test of whether to use sform that is getting confused by small voxel sizes. The data doesn't have to be oblique at all, if you have an sform of **I**β, where β is a sufficiently small number (< 0.2 seemed to trigger it for me), The sform is rejected, and the fallback to qform fails when qform_code is 0. 

I think if that can be addressed, we'll be good.

**Comment by gdevenyi** [comment]
Thanks for the detail @cookpa. I'm going to follow up with the report I got to see what the actual state of the NIFTI header was for reference here.

**Comment by gdevenyi** [comment]
Details on the problematic scan we had:
https://github.com/CoBrALab/RABIES/issues/160#issuecomment-892471093

**Comment by lassoan** [comment]
I have no preference on how to change the NIFTI code or error messages to deal with this issue.

My hope is that we can build up support for OME-Zarr (or similar modern file format) in the wider image computing community and that will offer enough incentives for researchers to leave behind NIFTI and its sform/qform mess for good.

**Comment by cookpa** [comment]
I think I found it:

https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1762-L1767

This fails if the voxels are small because the determinant of the sform matrix is below the threshold (1e-5). Perhaps this could safely be made smaller.

But without eliminating the test entirely, there's always going to be a minimum spacing before this error occurs. If the entries in sform matrix are sufficiently small, qform might be the better way to get the rotation anyway. But even if the qform is used, I think very small spacing could become problematic for computing the rotation / scale matrix inverses. 

Maybe users should be warned to use a more appropriate unit (eg, NIFTI_UNITS_MICRON) if the matrix determinant is below the threshold?

**Comment by cookpa** [comment]
Oh, actually other units won't help because they will get scaled to mm units

**Comment by Leengit** [comment]
@cookpa good sleuthing!  The 1e-5 threshold is quite demanding; anyone know why it is there?  For example, there are accurate methods for computing a matrix inverse that can handle determinants much, much smaller in absolute value than 1e-5.

**Comment by dzenanz** [comment]
PR #1868 introduced it:
https://github.com/InsightSoftwareConsortium/ITK/commit/34231b57021418fdb6afd4fcf5082a73b12969ed#diff-fa33a46a6dc41cde5d18ee8f63cb941794512e03c6377340b8d110fe584cfdfaR1756-R1760

I guess it is fine for MRIs, which have voxels ~ 1.0 mm. @hjmjohnson is there a problem reducing this to a much lower value?

**Comment by gdevenyi** [comment]
https://github.com/SimpleITK/SimpleITK/issues/1440

**Comment by dzenanz** [comment]
Gabriel, can you make a PR with your proposed changes (turn error into warning and more informative message)?

**Comment by dzenanz** [comment]
Also, can a mathematically-inclined person figure out a better threshold for determinant:
https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1764

**Comment by gdevenyi** [comment]
> Also, can a mathematically-inclined person figure out a better threshold for determinant:
> https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1764

I think solution might be to test the condition of the matrix and compare to epsilon, as suggested here, https://stackoverflow.com/a/13270760/4130016

**Comment by dzenanz** [comment]
> I think solution might be to test the condition of the matrix and compare to epsilon

It would be good if this found its way into your PR 😄

**Comment by gdevenyi** [comment]
To clarify here, after working through the logic, it looks like we have two things happening together
1. https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1764 which is resulting in some kinds of sforms being rejected

combined with
2. https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1971-L1980

Which, without an else condition, is falling through (and not, at least according to my reading, following the NIFTI spec, which says for `#define NIFTI_XFORM_UNKNOWN      0` that this should be followed:

```
   METHOD 1 (the "old" way, used only when qform_code = 0):
   -------------------------------------------------------
   The coordinate mapping from (i,j,k) to (x,y,z) is the ANALYZE
   7.5 way.  This is a simple scaling relationship:

     x = pixdim[1] * i
     y = pixdim[2] * j
     z = pixdim[3] * k


   No particular spatial orientation is attached to these (x,y,z)
   coordinates.  (NIFTI-1 does not have the ANALYZE 7.5 orient field,
   which is not general and is often not set properly.)  This method
   is not recommended, and is present mainly for compatibility with
   ANALYZE 7.5 files.
```

For a PR for this, I will add an else fallthrough, and print a warning, but the question is how should the final mapping be handled
1. Use the analyze method (qform = 0 above)
or
2. Use the qform anyways

**Comment by gdevenyi** [comment]
Following up on this again:
https://github.com/InsightSoftwareConsortium/ITK/blob/02e7c448b4e3b77f0e46afb66f92bb3be8995dd7/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1764

Something didn't sit right with me, so I went back to my linalg textbook and a matrix A is invertible if `det(A) != 0`. I wonder if this test was meant to be `fabs(vnl_determinant(mat)) >= 1e-5`

**Comment by cookpa** [comment]
If the header has nonzero sform or qform, and they cannot be used for reasons, I'd prefer to throw an error rather than fall back to method 1. Better no data than accidentally flipped data, IMO.

I think the logic is good as is:

* Attempt to use "method 1", Analyze backwards compatibility, only if qform_code == sform_code == 0.
* Else use sform if it's defined and orthonormal direction cosines can be recovered from it
* Else try to use qform
* Else throw an error

The only thing I would add is that after attempting and failing to use sform, the user should be warned that the attempt to use sform failed, and qform will be used as a fallback. Currently, that's a silent fallback. Arguably it should be an error too as it suggests something wrong with sform, but at least we are falling back to another transform that's actually in the header, rather than assuming ANALYZE.

**Comment by cookpa** [comment]
Regarding the threshold for the determinant, I found this:

```
  //: find weights below threshold tol, zero them out, and update W_ and Winverse_
  void            zero_out_absolute(double tol = 1e-8); //sqrt(machine epsilon)
```

https://github.com/vxl/vxl/blob/d771c601a2072afe46af8a80b8e480d0529d8f2f/core/vnl/algo/vnl_svd.h#L89-L90

So inversion will run into problems with voxels smaller than 1e-8, because the singular values will be zeroed out. This behavior can be changed in vnl_svd, but I'm not sure it's accessible from the wrapper vnl_matrix_inverse

**Comment by cookpa** [comment]
Regarding the threshold for the determinant, I found this in the matrix inversion code:

```
  //: find weights below threshold tol, zero them out, and update W_ and Winverse_
  void            zero_out_absolute(double tol = 1e-8); //sqrt(machine epsilon)
```

https://github.com/vxl/vxl/blob/d771c601a2072afe46af8a80b8e480d0529d8f2f/core/vnl/algo/vnl_svd.h#L89-L90

They suggest 1e-8 or sqrt(machine epsilon) as a threshold for the singular values to be zeroed out, but the class looks like it defaults to a threshold of zero. If we had spacing of 1e-8, the determinant would be 1e-24. 

I'll look more at the code, I'm thinking it might be better to just get the SVD decomposition directly and check it has the correct rank.

**Comment by Leengit** [comment]
Singular values (essentially eigenvalues) get multiplied together to determine the determinant, so even when 1e-8 is the right threshold for a singular value, it is probably not the correct threshold for a determinant.  Also, the smallest positive single-precision floating point number that can be represented (without resorting to subnormals representations) is 1.175494e-38, and its square root is not 1e-8.

More importantly, rigorously it is the matrix conditioning number rather than its determinant that should be checked.  Is that check a possibility?

**Comment by gdevenyi** [comment]
> More importantly, rigorously it is the matrix conditioning number rather than its determinant that should be checked. Is that check a possibility?

Yes, if we just compute SVD directly its the ratio of the largest to smallest eigenvalues.

**Comment by cookpa** [comment]
Using the matrix condition : 

https://github.com/cookpa/ITK/blob/2a6a365b8a6ee1a715254c1c3478666c4e8b8e6f/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1762-L1767

This reads small (18 micron) voxels that previously failed. I'm not sure on the best way to formally test this, as any image created with this class will contain both sform and qform.

**Comment by gdevenyi** [comment]
> Using the matrix condition :
Awesome, I couldn't find something that just outputted the condition number.

This fix will solve the immediate issue, I think we can leave the logic adjustment to a seperate PR?

**Comment by cookpa** [comment]
I put in a PR for the condition number stuff. I could not find a good place to insert a warning without doing more refactoring, so I left that out. IMO the only time to warn is if we can't use sform AND sform_code == NIFTI_XFORM_SCANNER_ANAT.
