### ISSUE TITLE
Unicode support for filenames

### ISSUE THREAD

**Issue by Nekto89** [InsightSoftwareConsortium/ITK#2693]
Currently interfaces of ImageFileReader/ImageFileWriter receive filenames in locale-specific encoding if I understand correctly. So if I have a filename in UTF-8/UTF-16 that can't be represented in this locale, I won't be able to use this file. This is a problem on Windows which doesn't use UTF-8 by default for fopen/fstream. Suggestions for IO objects that are part of ITK and use fopen/fstream:
- allow users to provide filename in UTF-8 or UTF-16 and do conversion internally. On Windows ITK can convert filename to UTF-16 and use std::wstring for fopen/fstream. This won't change anything for platforms where UTF-8 is already the default encoding.
- allow users to open a file on their side and pass std::istream to ITK. This might also give users the ability to use memory instead of files.

**Comment by dzenanz** [comment]
As each image IO handles files differently, getting them all to accept `std::istream` in addition to `filename` is going to be very hard, and might not even be possible for some of them.

When somebody needs special characters, they can enable [UTF8 as the default code page](https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#UTF-8) since a few years ago. So the cost of this big refactoring is not really justified. If you are writing an application and you want it to support Unicode, then you can set the [utf8 code page for the application via an API](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160#utf-8-support) in order to not be at the mercy of the end-user.

**Comment by Nekto89** [comment]
And what about users who still use older versions of Windows (that are still supported)?

**Comment by dzenanz** [comment]
Only [around 20%](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide) use older versions of Windows. That will only reduce in the future. And when you further subdivide it into regions which have need for characters outside of [US-ASCII](https://en.wikipedia.org/wiki/Windows-1252), that is an increasingly small number. However they dealt with it until, they can still do that (mostly naming files `Dzenan Zukic.png` instead of `Dženan Zukić.png`).

Don't get me wrong - I would like this fixed properly, but the cost of doing so is high and we have limited resources.
