### ISSUE TITLE
LabelImageToLabelMapFilter takes a long time to complete on an empty image

### ISSUE THREAD

**Issue by Janneke80** [InsightSoftwareConsortium/ITK#2741]
The LabelImageToLabelMapFilter takes a long time to complete on an empty image.

The following code snippet can reproduce the bug.

     auto p_filter = itk::LabelImageToLabelMapFilter<itk::Image<unsigned char, 3>>::New();
     auto p_image = itk::Image<unsigned char, 3>::New();
     p_image->SetRegions(itk::Size<3>{ 0, 0, 0 });
     p_image->Allocate(true);
 
     p_filter->SetInput(p_image);     
     p_filter->Update(); 

Takes about 16 seconds to complete on my PC.

```none
```

### Reproducibility

ITK version 5.1.2

Windows, CMake 3.18.2, Visual Studio 16.7.2

**Comment by dzenanz** [comment]
I cannot reproduce with master. The following program completes in a fraction of a second in both debug and release modes:
```cpp
#include "itkLabelImageToLabelMapFilter.h"

int
main(int argc, char * argv[])
{
  auto p_filter = itk::LabelImageToLabelMapFilter<itk::Image<unsigned char, 3>>::New();
  auto p_image = itk::Image<unsigned char, 3>::New();
  p_image->SetRegions(itk::Size<3>{ 0, 0, 0 });
  p_image->Allocate(true);

  p_filter->SetInput(p_image);
  p_filter->Update();

  return EXIT_SUCCESS;
}
```

**Comment by Nekto89** [comment]
There is a problem in ImageRegionSplitterSlowDimension - zero is divided by zero and then casted to unsigned int. Resulting value is unspecified in this case. So number of work units probably may change depending on compiler version.

On my machine currently ImageRegionSplitterSlowDimension::GetNumberOfSplitsInternal returns 1073741824. This value is getting truncated in PoolMultiThreader::SingleMethodExecute() to 128 so LabelImageToLabelMapFilter is calling ThreadedGenerateData only 128 times instead of 1073741824 for zero-sized image.

https://github.com/InsightSoftwareConsortium/ITK/blob/eec9fe67056bfb5c693a4915b86eac9271e1dc83/Modules/Core/Common/src/itkImageRegionSplitterSlowDimension.cxx#L48

**Comment by Nekto89** [comment]
TBBMultiThreader doesn't limit number of work units, so all 1073741824 are getting into tbb::parallel_for

**Comment by dzenanz** [comment]
It should be a simple fix. Anyone willing to take it on?

**Comment by Janneke80** [comment]
Note that the same issue seems to exist in itkImageRegionSplitterDirection.cxx
