### ISSUE TITLE
Use zstd compression in NRRD and MetaIO

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#348]
[[Background discussion](https://discourse.itk.org/t/add-a-parallel-compression-method-to-nrrd-and-or-metaimage/696)]

`zstd`'s advanced API which supports multithreading has [recently](https://github.com/facebook/zstd/issues/1248#issuecomment-449587165) entered staging area with intention to be moved into stable API. Now is a great time to make use of it, before ITKv5.0 is released.

**Comment by neurolabusc** [comment]
This seems related to this [discussion](https://discourse.itk.org/t/add-a-parallel-compression-method-to-nrrd-and-or-metaimage/696/26). It does seem like the NRRD format needs to be updated to specifically include this. 
I do have a couple comments

1. One option for faster compression in a manner that is fully compatible with existing NRRD data is to use PIGZ for your compression. The recent releases of pigz allow named pipes that allow direct compression, without having to save the uncompressed data to disk first. This offers much faster compression on parallel computers using an existing format. Because it uses the GZ deflate, it is not as fast to compress or decompress as zstd, but it works with all existing tools.
2. Since this will break compatibility with previous NRRD tools, I would carefully evaluate whether zstd is the ideal choice for your application. zstd is an exceptional generate purpose compression method that is very fast to compress and decompress. However, in my experience its primary weakness is precisely with the data we store in NRRD files: long streams of 16-bit or 32-bit values with strong correlation of the most significant bits across values. In my experience, combining a simple byte-shuffling pre-filter (e.g. blosc) dramatically improves the performance (both in terms of size and speed) of zstd. The zstd developers are aware of this, and I think their next tools will fill this niche. My sense is that such a future tool (or blosc) would be better suited for NRRD than a pure zstd compression.

**Comment by hjmjohnson** [comment]
@dzenanz FYI:  I have been assisting zstd with updating their CMake implementation.  The community has been fairly receptive to changes that increase it's use.

**Comment by jamesobutler** [comment]
Just adding updated information:

`zstd` v1.4.0 was released April 16th, 2019.
https://github.com/facebook/zstd/releases/tag/v1.4.0

> Advanced API
> 
> The main focus of the v1.4.0 release is the stabilization of the advanced API.

Current release is now v1.4.3
https://github.com/facebook/zstd/releases/tag/v1.4.3

**Comment by neurolabusc** [comment]
Two recent experiments I did may be relevant to this thread. These both focus on making Gzip compression faster, which would retain compatibility with the current NRRD format. One could use this acceleration to use a better compression level, getting a little closer to zstd. 

1.) Since pigz is based on zlib, it can be recompiled with the accelerated CloudFlare zlib. Here is a simple CMake script that builds [pigz](https://github.com/neurolabusc/pigz) with the CloudFlare zlib:

```
git clone https://github.com/neurolabusc/pigz.git
cd pigz
mkdir build && cd build
```

2.) ITK uses znzlib to read/write NIfTI images. My [accelerated znzlib](https://github.com/neurolabusc/znzlib) demonstrates two methods to accelerate writing gzip images. First, the NIfTI IO can be built using the CloudFlare zlib which is faster than the system zlib. Second, the user can provide an environment variable to request that data is piped to pigz. Only a few lines of code are modified, yielding a dramatic performance increase. I do think the same strategy could be used for the NRRD writing. As my project demonstrates, file writing for uncompressed data and piped pigz are the same, so one can generally use the same existing well tested routines.

**Comment by dzenanz** [comment]
The low hanging fruit is [zlib-ng](https://github.com/zlib-ng/zlib-ng), as pointed out in [a VTK forum discussion](https://discourse.vtk.org/t/cloudflare-zlib/2330/5?u=dzenanz).

**Comment by gdevenyi** [comment]
Also #416

**Comment by dzenanz** [comment]
I am giving up on this as `zlib-ng` was integrated via #2708 and #2803, adding zstd to NRRD and MetaIO is major undertaking, and there is ongoing OME-Zarr effort.
