### ISSUE TITLE
Change doxygen layout

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#3666]
I think it would be better if detailed class description is at the top of the page, and not buried after heaps of public definitions inside a class, many of the pretty standard and therefore not overly interesting.

Relevant doxygen docs: https://www.doxygen.nl/manual/customize.html#layout

**Comment by dzenanz** [comment]
I was just looking at elastix' documentation, and it has the detailed description at the top of the page (e.g. [DeformationFieldTransform](https://elastix.lumc.nl/doxygen/classelastix_1_1DeformationFieldTransform.html)). Could this be achieved simply by moving [`detaileddescription` element](https://github.com/InsightSoftwareConsortium/ITK/blob/a00eb3914d0ab4e4973180f295db56b736aa1ef4/Documentation/Doxygen/DoxygenLayout.xml#L79) to near the top, similar to elastix' [doxygenlayout.xml](https://github.com/SuperElastix/elastix/blob/3979978aaf712c3c78cacdf64eb451aff6eb553d/dox/doxygen/doxygenlayout.xml#L29)?

**Comment by dzenanz** [comment]
@N-Dekker @jhlegarreta @blowekamp can anyone try this easily?

**Comment by jhlegarreta** [comment]
I am really sorry, @dzenanz, but I cannot afford trying this; don't remember having installed Doxygen, and I am really overwhelmed by other tasks at the moment. I confess that I have other Doxygen-related ITK issues in my ToDo list, but I have not enough bandwidth or energy to tackle them instead of other tasks. Again, really sorry for not being helpful here.
