### ISSUE TITLE
Wrap double and std::complex<double> by default, instead of the float versions

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#435]
Right now the default options wrap `float` and `std::complex<float>`. However, some linear algebra classes, like [VariableSizeMatrix only wraps double](https://github.com/InsightSoftwareConsortium/ITK/blob/1b032679fc1a50fc4821ab2a31d3e33337b6d5bc/Modules/Core/Common/wrapping/itkVariableSizeMatrix.wrap). 

What do you think about wrapping double by default, and float optionally?
@thewtex @blowekamp @hjmjohnson @dzenanz @glehmann

**Comment by thewtex** [comment]
We wrap `float` and `std::complex< float >` by default now because this results in better memory consumption for large images. Usually this is a better tradeoff versus the gain in precisions from `double`. `double` is still often used for intermediate computations.

We are looking at building the binaries with shared, which will help reduce the binary size and could make wrapping `double`, too, feasible...

**Comment by phcerdan** [comment]
:+1:
