### ISSUE TITLE
itksys::SystemTools::FileIsDirectory does not handle accented characters

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#540]
### Description

As discussed on Discourse:

  https://discourse.itk.org/t/handling-of-combined-accents-by-itk-system-tools/1619/5

reported by Tim Evain,

> I’m using the itksys tools to do some file parsing and I’ve encountered a nasty problem with some filepaths containing accented characters.
For example I have this folder name in my database : “aorte_déroulée”. It appears that in fact, the “é” symbol is a “e” char followed by a combining acute accent char (I think that data came from a MacOS station).
When using itksys::Directory::Load() on the parent folder, the given string is then “aorte_de´roule´e”, which is fine. Problem is that this path is not recognized as valid afterward: using itksys::Directory::Load("[…]/aorte_de´roule´e") or itksys::SystemTools::FileIsDirectory("[…]/aorte_de´roule´e") fails. Replacing directly by the full char “é” in the string doesn’t help either.

### Expected behavior

Accented characters are handled.

### Actual behavior

- itksys::Directory::Load() fails on (Directory.cxx, l 121) 
```
  srchHandle = _wfindfirst_func(
    (wchar_t*)Encoding::ToWindowsExtendedPath(buf).c_str(), &data);
```
where `srchHandle` is `-1` 
- itksys::SystemTools::FileIsDirectory fails on (SystemTools.cxx, l 2902)
```
  DWORD attr =
    GetFileAttributesW(Encoding::ToWindowsExtendedPath(name).c_str());
```
where `attr == INVALID_FILE_ATTRIBUTES`

### Reproducibility

Recent ITK Git `master` (with updated KWSys) was tested.

### Environment

> It appears to be a Windows-specific issue, as tests on MacOS and Linux run fine. I’ve tracked down the problem to:

### Additional Information

Test case from Tim attached.
[CombinedAccents_TestCase.zip](https://github.com/InsightSoftwareConsortium/ITK/files/2901365/CombinedAccents_TestCase.zip)

CC: @bradking

**Comment by bradking** [comment]
When KWSys's `Encoding*.*` sources are compiled, what is the value passed to the compiler as the `KWSYS_ENCODING_DEFAULT_CODEPAGE` definition?

**Comment by dzenanz** [comment]
[Line 131](https://github.com/InsightSoftwareConsortium/ITK/blob/f9638315f052a68e98083cf22417530c6015f89e/Modules/ThirdParty/KWSys/src/KWSys/Directory.cxx#L131): `this->Internal->Files.push_back(Encoding::ToNarrow(data.name));` screws up the name. I think that encoding is the [default](https://github.com/InsightSoftwareConsortium/ITK/blob/f9638315f052a68e98083cf22417530c6015f89e/Modules/ThirdParty/KWSys/src/KWSys/CMakeLists.txt#L191) `CP_ACP`.

**Comment by dzenanz** [comment]
This is an updated example (which compiles):
```C++
#include <string>
#include <iostream>

#include <itksys/Directory.hxx>
#include <itksys/SystemTools.hxx>

int main(int argc, char * argv[])
{
    std::string FolderToParse = "./TopFolder";

    // make an absolute path from whatever is passed in
    std::string AbsolutePath = itksys::SystemTools::CollapseFullPath(FolderToParse);

    // work in Unix filename conventions
    itksys::SystemTools::ConvertToUnixSlashes(AbsolutePath);

    itksys::Directory directory;
    directory.Load(AbsolutePath);

    unsigned numFiles = directory.GetNumberOfFiles();
    for (unsigned int file_idx = 0; file_idx < numFiles; file_idx++)
    {
       std::string CurrFile = directory.GetFile(file_idx);
       std::string FullFilePath = AbsolutePath + "/" + CurrFile;
       if (CurrFile == "." || CurrFile == "..")//if current folder or parent, continue
       {
          continue;
       }
       //if (itksys::SystemTools::FileIsDirectory(FullFilePath))
       {
          std::cout<<FullFilePath;
       }
    }

    return 0;
}
```

**Comment by dzenanz** [comment]
The problem is semantic: ASCII does not properly represent the string `aorte_déroulée`. The correct solution is probably to keep the list of [files](https://github.com/InsightSoftwareConsortium/ITK/blob/f9638315f052a68e98083cf22417530c6015f89e/Modules/ThirdParty/KWSys/src/KWSys/Directory.cxx#L27) as `wstring`, and cast to `char*` only if that function signature is called. Of course, another signature such as `const std::wstring& GetFileW(unsigned long dindex) const` should be provided for those who want to support non-ASCII characters.

@thewtex @blowekamp @hjmjohnson I don't think it make sense to introduce better Unicode support now, because we would probably have to [resort](https://stackoverflow.com/a/6318604/276168) to [boost::filesystem](https://www.boost.org/doc/libs/1_69_0/libs/filesystem/doc/index.htm) or something similar. I think it is better to wait until we can require C++17 and use the built-int [file system](https://en.cppreference.com/w/cpp/header/filesystem) support.

**Comment by bradking** [comment]
If ITK were built with `-DKWSYS_ENCODING_DEFAULT_CODEPAGE=CP_UTF8` then narrow strings would be in UTF-8 and have no problem with non-ascii characters.

**Comment by dzenanz** [comment]
With PR #546, the strings appears correctly in the debugger, Git Bash, and when redirected to a file like this: 
`C:\Users\Dzenan\Desktop\CombinedAccents_TestCase>Debug\CombinedAccents_test_app.exe >out.log`. In CMD, it still looks garbled up. But I guess that is not a problem?

**Comment by bradking** [comment]
@dzenanz great.  In order to print to a Windows Console properly the application needs to convert from its internal UTF-8 encoding to wide character, and then back to whatever multi-byte encoding corresponds to the console's active code page (`CP_ACP`).  See [code in cmake](https://gitlab.kitware.com/cmake/cmake/blob/v3.13.4/Source/cm_codecvt.cxx#L162-177) as an example.
